name = "algorinfo"
fullurl = "https://www.algorinfo.com"
sitemap_path = "/"
# gzipped file
compress = false
output_dir = "public"

[[routes]]
loc = "/"
# (always|hourly|daily|weekly|monthly|yearly|never) 
changefreq = "weekly"
mobile = true
priority = 1.0
sitemap = true
robot = true

[[routes]]
loc = "dolar"
changefreq = "always"
mobile = true
priority = 0.5
sitemap = true
robot = true

[[routes]]
loc = "trends"
changefreq = "always"
mobile = true
priority = 0.3
sitemap = true
robot = false
